name: stats285
channels:
  - conda-forge
  - defaults
dependencies:
  - blas[build=mkl]
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - catboost
  - lightgbm
  - sqlalchemy
  - google-auth
  - google-cloud-sdk
  - google-cloud-aiplatform
  - dask
  - dask-jobqueue
  - pip
  - pip:
    - git+https://github.com/adonoho/EMS.git@v0.0.16
    - ucimlrepo
variables:
  MKL_NUM_THREADS: '1'
  OPENBLAS_NUM_THREADS: '1'
